spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: ERROR
  org.hibernate.type: ERROR
  org.hibernate.type.BasicTypeRegistry: ERROR